### ISSUE TITLE
DPL-594 [BUG] Traction: Search functionality breaks or takes longer to search the matching records on the Pacbio 'Runs' tab.

### ISSUE THREAD

**Issue by SujitDey2022** [sanger/traction-ui#1003]
**Describe the bug**
Search functionality breaks or takes longer to search the matching records on the Pacbio 'Runs' tab.
![image](https://user-images.githubusercontent.com/115623404/207635875-dca97b13-d1ce-4246-8fa2-e91adb2710b4.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Navigate to Pacbio > Runs from https://traction.psd.sanger.ac.uk/#/dashboard
2. Enter run 'Name' in the filter search box available above the record list.

**Expected behaviour**
System should display the records matching the entered text.

**Actual/Existing behaviour**
System does not perform the search or takes longer to display the matching records from the list.

**Comment by stevieing** [comment]
Tasks needed to improve performance:
- Add pagination in the service for pacbio sequencing runs
- Modify the front end to use bespoke pagination component
- Modify the store to make correct use of pagination i.e. only return a number of records rather than all of them
- Modify the store so we only return the runs themselves without any associations - we do not need plates, wells or libraries
- Modify the search so that it does not query all of the data that has been returned. We can use this as a search to the service
- Create a search in the service for the filter

Note: Once this has been done we should be able to roll out this functionality to other pages
