### ISSUE TITLE
DPL-1093-2 - As developers we want to find out how to modify the e2e fixtures so we can re-use the factory wrapper that we are creating so we do not have to duplicate requests

### ISSUE THREAD

**Issue by stevieing** [sanger/traction-ui#1659]
**Description**
As developers we want to find out how to modify the e2e fixtures so we can re-use the factory wrapper that we are creating so we do not have to duplicate requests.

**Who the primary contacts are for this work**
Steve / Seena / Dasun / Stephen

**Additional context or information**
Currently the e2e fixtures are a direct copy of the data folder. We are planning to move that to a factory. We would like to do the same for the e2e tests

**Comment by stevieing** [comment]
Example:

```
import RequestFactory from '../../../support/factoryHelper.js'

const smrtLinkVersionRequestFactory = RequestFactory('tractionPacbioSmrtLinkVersions', false)

describe('Pacbio Runs view', () => {
  it('Visits the pacbio runs url', () => {
    cy.intercept('/v1/pacbio/runs?page[size]=25&page[number]=1&include=plates', {
      fixture: 'tractionPacbioRuns.json',
    })
    cy.intercept('/v1/pacbio/smrt_link_versions', {
      // fixture: 'tractionPacbioSmrtLinkVersions.json',
      statusCode: 201,
      body: smrtLinkVersionRequestFactory.content,
    })
    cy.visit('#/pacbio/runs')
    // Check filters are visible
    cy.get('#filterInput').should('be.visible')
    cy.get('#filterValue').should('be.visible')
    cy.get('#filterValue').children().and('contain', 'Name')
    cy.get('#run-index').contains('tr', '5')
    cy.get('#startRun-12')
    cy.get('#editRun-12')
    cy.get('#generate-sample-sheet-12')
    cy.get('#run-index')
      .first()
      .within(() => {
        cy.get('#id').should('have.length.greaterThan', 0)
        cy.get('#name').should('have.length.greaterThan', 0)
        cy.get('#state').should('have.length.greaterThan', 0)
        cy.get('#sequencing_kit_box_barcodes').should('have.length.greaterThan', 0)
        cy.get('#dna_control_complex_box_barcode').should('have.length.greaterThan', 0)
        cy.get('#system_name_and_version').find('.badge').should('have.length.greaterThan', 0)
      })
  })
})
```

We have decided to keep this simple. We are using relative paths which is fine.

**Comment by dasunpubudumal** [comment]
In [`RequestFactory`](https://github.com/sanger/traction-ui/blob/ead11fbc234f491e27fda63fb0ade4bc18fbb259/tests/support/factoryHelper.js#L16C1-L38C2), we used [`fs` module](https://nodejs.org/api/fs.html) from Node.js to load the fixture into the factory.

Sadly, Cypress cannot support this, as it is being executed in a browser context, along with its own Node.js runtime for file system and network access. If we are to use this runtime, we are supposed to use it with [`cy` helper](https://docs.cypress.io/api/commands/readfile) provided along with Cypress. Here's an excerpt from [Cypress documentation](https://www.cypress.io/how-it-works):

> Behind Cypress is a Node.js server process. Cypress and the Node.js process constantly communicate, synchronise, and perform tasks on behalf of each other. Having access to both parts (front and back) gives us the ability to respond to your application’s events in real time, while at the same time work outside of the browser for tasks that require a higher privilege.

Because Cypress uses its own Node.js runtime, we could not use our `RequestFactory` as it currently was, as it was using the native Node runtime to access the file system.

Therefore, we discussed updating the `RequestFactory` to accommodate both unit and e2e tests. **Dynamic Imports** were discussed as a potential option for this.
