### ISSUE TITLE
DPL-439 As a SSM (Caroline H) in ToL I would like to be able to query QC data from the extraction processes in SciOps from the MLWH database so that I can investigate runs with low yields.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/traction-ui#855]
**User story**
As a SSM (Caroline H) in ToL
 I would like to be able to query QC data from the extraction processes in SciOps from the MLWH database 
 so that I can investigate runs with low yields.

**Who are the primary contacts for this story**
Caroline H
Charlie H

_**Need to identify a UAT tester for this from the DNAP extraction lab for this.**_ 

- James W
- Lucy Kitchin
- Michelle Smith
- Esther Mellado Gomez

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] A menu item QC Results or similar on the top menu next to reception
- [ ] Users must enter in a valid barcode
- [ ] Users must choose the type of QC results from a list (see below)
- [ ] Users must enter in a value (numeric or string) depending on the QC type
- [ ] Users can select a unit from a list (see below) - default to blank
- [ ] Users can submit valid data and receive confirmation and then proceed to enter a new qc record
- [ ] Users receive a meaningful error message if data is invalid
- [ ] Valid data is recorded in a qc_results table in traction service (see qc_results table in Sequencescape)
- [ ] Valid data entered is recorded in the MLWH table qc_results or equivalent. This may need more info or moving into another story as ToL will need to be able to indentify the samples so an asset id will not be enough as they will need to be able to trace to source
- [ ] Styling should follow Tailwind rather than Bootstrap as it is being deprecated.

We intend the solution to be as flexible as possible without taking too much developer time.

**Additional context**

QC Results that can be recorded

| QC Type | Data Type |
| ------- | --------- |
| Tissue mass (mg) | Numeric |
| Qubit (ng/uL) | Numeric | 
| Extraction yield (ng) | Numeric |
| Nanodrop concentration (ng/ul) | Numeric |
| 260/ 230 ratio extraction | Numeric |
| 260/ 280 ratio extraction | Numeric |
| Femto profile description | Text |
| Femto profile link | Text/URL |
| GQN with threshold at 30Kb | Numeric | 
| Extraction result (pass/fail/hold) | Text |
| Yield post 0.45X clean up | Numeric |
| Qubit (ng/ul) post 0.45X clean up | Numeric |
| Mode length of DNA sheared for PacBio (bp)  | Numeric |
| GQN with threshold at 10Kb | Numeric | 
| Qubit (post shear:SPRI ng/ul in 45.4uL) | Numeric | 
| Nanodrop concentration (ng/ul) | Numeric | 
| 260/280 ratio post shear:SPRI | Numeric |
| 260/230 ratio post shear:SPRI | Numeric |
| Pre-library yield | Numeric |
| % DNA recovery (into shear - after SPRI) | Numeric |
| Shear/SPRI result (pass/fail/hold) | Numeric |

Unit types
| Units |
| ----- |
| ***Blank*** |
| ng/ul |
| ng |
| mg |
| % |

**Comment by stevieing** [comment]
Some thoughts:

- Althought this qc data is from extractions it makes sense to put it here. It is for long read so follows the strategy for Long Read. It will also be used for downstream qc for Pacbio and ONT. 
- It makes sense to check the barcode. We could put a source field so if it extractions it could check it exists and pull the source barcode. This means that when ToL move to STS we wouldn't need to do extra work.
- The qc_results table in MLWH may not be fit for this purpose. It is very much tied to the sample table so is Sequencescape specific. It would also make sense to use barcodes which should include the soource. It makes sense for this table to be stand alone. ToL will pull data into Tableau and combine it with their own data so it needs to be as simple and accessible as possible
-

**Comment by stevieing** [comment]
Example qc data:
[LR Extractions.xlsx](https://github.com/sanger/traction-ui/files/9308767/LR.Extractions.xlsx)

**Comment by KatyTaylor** [comment]
**Write up of a couple of meetings: Hermione / Lucy on 24/08/2022, and the same + Esther on 26/08/22**

Showed them in-progress UI:

![Screenshot 2022-08-30 at 10 26 15](https://user-images.githubusercontent.com/10407809/187401376-8990073d-27cc-4114-9cdb-63f0613720df.png)

![Screenshot 2022-08-30 at 10 25 26](https://user-images.githubusercontent.com/10407809/187401396-1176f007-98ed-4613-8e57-2f70fdd77c30.png)

**Feedback**

Summary:
1. They would continue to use their spreadsheet
    - They fill this out gradually throughout the week as they generate data
2. They would have double enter data into the new Traction page
    - If OK with ToL they would choose to do this once a week, entering all the results for a sample at once. At the expected throughput this would mean filling out the page 96 times per week.
 
Post-meeting PSD thoughts:
- Using spreadsheets as main form of tracking is a bit fragile and not very scalable when the numbers start racking up for the ToL project – using a LIMS would be better long term
- Having the QC data in the Multi-LIMS Warehouse is better for ToL (and customers of other project), because they can report on it and link it up easily with other data e.g. from the sequencing
 
Agreed with Esther - ideal solution is to make this feature in a way where they can just use the Traction page (where it is redesigned to be useful to them and provide extra value above the spreadsheet - or could in future) & take those columns out of the spreadsheet - one step on a journey towards using LIMS rather than spreadsheets as the central place to track samples.
 
From meeting, main reasons the spreadsheet is useful:
- Can enter data for multiple samples in one go, by going down the rows in the spreadsheet
- The QC data is in the same place as some of the other data relating to the sample
- There is a way (copy paste) of transferring QC data from the extractions spreadsheet into the downstream PacBio library prep spreadsheet – the library prep team do have access to the extractions spreadsheet but prefer to duplicate the data into their sheet
- There is a comments box where they can note down if anything went wrong or was unusual
- I noticed that there are several extra fields in the QC sections which are not mentioned in my task – so I assume they would also want to track these
 
We discussed some hand-drawn pictures (below) showing how we could change the Traction pages to satisfy some of the bullet points above. The main changes are that I’ve introduced a concept of ‘batches’ and then entering and reviewing data is done for a whole batch at a time. 

Menu page:
![0-menu](https://user-images.githubusercontent.com/10407809/187403833-91f1a1b1-bac9-4816-ada7-727bf16c73ba.jpg)

Create batch page:
![1-create-batch](https://user-images.githubusercontent.com/10407809/187403878-7b9a6527-cf3a-424f-8b78-a75907c1c609.jpg)

Enter results page:
![2-enter-results](https://user-images.githubusercontent.com/10407809/187403894-841e22d2-eef1-4203-9631-88260829c8ce.jpg)

Review page:
![3-review-pass-fail](https://user-images.githubusercontent.com/10407809/187403915-5c0d7c88-96f6-4d64-9a2c-35653231a457.jpg)

**Feedback on these drawings**
Generally feedback was positive, with a few comments:
- They'd want to see the full history of values on page, not just the 'latest' (otherwise were talking about using comments box as workaround)
- They'd want a comments box, one after the extractions and one after the shear/SPRI (could be associated with each pass/fail)
- 'Review' page should work regardless of whether or not all values are complete for a sample
- 'Review' page should allow to tick multiple batches so can cross compare across batches
- Possibility of automated pass / fail decision assistance in future (but would always need manual override)
- Calculations would be needed e.g. concentration - calc always same but would need to enter volume as could change

**Comment by stevieing** [comment]
Closed in favour of DPL-477, DPL-478 and DPL-479. Stories have been linked.
